<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>CloudFabric.Projections.CosmosDb</PackageId>
        <Version>0.0.1</Version>
        <Authors>CloudFabric Developers</Authors>
        <Company>CloudFabric</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Tech-Fabric/CloudFabric.EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CloudFabric.Projections\CloudFabric.Projections.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.47.2" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Polly" Version="8.5.2" />
    </ItemGroup>

</Project>