<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>CloudFabric.Projections</PackageId>
        <Version>0.0.1</Version>
        <Authors>CloudFabric Developers</Authors>
        <Company>CloudFabric</Company>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CloudFabric.EventSourcing.Domain\CloudFabric.EventSourcing.Domain.csproj" />
        <ProjectReference Include="..\CloudFabric.EventSourcing.EventStore\CloudFabric.EventSourcing.EventStore.csproj" />
        <ProjectReference Include="..\CloudFabric.Projections.Attributes\CloudFabric.Projections.Attributes.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.3" />
        <PackageReference Include="Polly.Core" Version="8.5.2" />
        <PackageReference Include="System.IO.Hashing" Version="9.0.3" />
    </ItemGroup>

</Project>