<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>CloudFabric.EventSourcing.AspNet.InMemory</PackageId>
    <Version>0.0.1</Version>
    <Authors>CloudFabric Developers</Authors>
    <Company>CloudFabric</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Tech-Fabric/CloudFabric.EventSourcing</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Implementations\CloudFabric.EventSourcing.EventStore.InMemory\CloudFabric.EventSourcing.EventStore.InMemory.csproj" />
    <ProjectReference Include="..\..\Implementations\CloudFabric.Projections.InMemory\CloudFabric.Projections.InMemory.csproj" />
    <ProjectReference Include="..\CloudFabric.EventSourcing.AspNet\CloudFabric.EventSourcing.AspNet.csproj" />
  </ItemGroup>

</Project>
