<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CloudFabric.EventSourcing.EventStore.Postgresql</RootNamespace>
        <AssemblyName>CloudFabric.EventSourcing.EventStore.Postgresql</AssemblyName>
        <PackageId>CloudFabric.EventSourcing.EventStore.Postgresql</PackageId>
        <Version>0.0.1</Version>
        <Authors>CloudFabric Developers</Authors>
        <Company>CloudFabric</Company>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CloudFabric.EventSourcing.Domain\CloudFabric.EventSourcing.Domain.csproj" />
        <ProjectReference Include="..\..\CloudFabric.EventSourcing.EventStore\CloudFabric.EventSourcing.EventStore.csproj" />
        <ProjectReference Include="..\..\CloudFabric.Projections\CloudFabric.Projections.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
    </ItemGroup>

</Project>