<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>CloudFabric.Projections.Postgresql</PackageId>
        <Version>0.0.1</Version>
        <Authors>CloudFabric Developers</Authors>
        <Company>CloudFabric</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Tech-Fabric/CloudFabric.EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CloudFabric.Projections\CloudFabric.Projections.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="9.0.3" />
    </ItemGroup>

</Project>